-- ============================================================================
-- Campus Leave Agent - Supabase / PostgreSQL migration
--
-- Run this ONCE in the Supabase SQL Editor (paste the whole file, press Run).
-- It is safe to run again: every statement is idempotent.
--
-- One Supabase project gives you one PostgreSQL database, so the brief's two
-- stores live here as two clearly separated table namespaces:
--
--   leave_*  domain store   students, holidays, policy, requests, notifications
--   agent_*  runtime store  threads, messages, runs, steps, tool calls
--
-- Nothing in leave_* knows about agents, and nothing in agent_* knows about
-- leave. Section 3 of the README explains the trade-off.
--
-- No extensions are required. sha256() and encode() are built into
-- PostgreSQL 11+, so this does not depend on pgcrypto living in the
-- `extensions` schema (which is where Supabase puts it, and which would be
-- invisible to a function pinned to `search_path = public`).
-- ============================================================================


-- ============================================================================
-- DOMAIN STORE
-- ============================================================================

create table if not exists public.leave_student (
    id            bigint generated by default as identity primary key,
    roll_no       text    not null unique,
    name          text    not null,
    dept          text    not null,
    leave_balance integer not null check (leave_balance >= 0)
);

create table if not exists public.leave_holiday (
    id           bigint generated by default as identity primary key,
    holiday_date date not null unique,
    name         text not null
);

-- The business rule lives here, as data. Not in a prompt, not in Python.
create table if not exists public.leave_policy (
    name  text primary key,
    value integer not null check (value >= 0)
);

create table if not exists public.leave_request (
    id         bigint generated by default as identity primary key,
    student_id bigint  not null references public.leave_student(id),
    start_date date    not null,
    end_date   date    not null,
    days       integer not null check (days > 0),
    reason     text    not null,
    status     text    not null check (status in ('approved', 'withdrawn')),
    created_at timestamptz not null default now(),
    -- Makes apply_leave safe to repeat on its own, with no key involved.
    unique (student_id, start_date, end_date)
);
create index if not exists leave_request_by_student
    on public.leave_request (student_id, start_date);

create table if not exists public.leave_notification (
    id         bigint generated by default as identity primary key,
    roll_no    text not null,
    message    text not null,
    -- Same student, same message, same day => one row. The second safe-to-
    -- repeat side effect.
    dedupe_key text not null unique,
    created_at timestamptz not null default now()
);

-- Every write effect stores its key and its result in the same transaction as
-- the effect itself. A crash between the effect and the worker recording it
-- replays the stored result instead of doing the work twice.
create table if not exists public.leave_idempotency (
    key        text primary key,
    tool_name  text  not null,
    result     jsonb not null,
    created_at timestamptz not null default now()
);


-- ============================================================================
-- AGENT RUNTIME STORE
-- ============================================================================

create table if not exists public.agent_thread (
    id         uuid primary key,
    student_id text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.agent_message (
    id         bigint generated by default as identity primary key,
    thread_id  uuid    not null references public.agent_thread(id),
    seq        integer not null,
    role       text    not null check (role in ('user', 'model')),
    text       text    not null,
    created_at timestamptz not null default now(),
    unique (thread_id, seq)
);

create table if not exists public.agent_run (
    id               uuid primary key,
    thread_id        uuid    not null references public.agent_thread(id),
    status           text    not null check (status in
                         ('queued', 'running', 'succeeded', 'failed', 'cancelled', 'dead')),
    model            text    not null,
    tokens_in        integer not null default 0,
    tokens_out       integer not null default 0,
    attempts         integer not null default 0,
    max_attempts     integer not null default 3,
    available_at     timestamptz not null default now(),  -- not claimable before this
    lease_owner      text,                                -- worker holding the run
    lease_until      timestamptz,                         -- when that claim goes stale
    cancel_requested boolean not null default false,
    error_code       text,
    created_at       timestamptz not null default now(),
    started_at       timestamptz,
    finished_at      timestamptz
);
create index if not exists agent_run_claimable
    on public.agent_run (status, available_at, created_at);

create table if not exists public.agent_run_step (
    id         bigint generated by default as identity primary key,
    run_id     uuid    not null references public.agent_run(id),
    seq        integer not null,
    kind       text    not null check (kind in ('model', 'tool')),
    tokens_in  integer not null default 0,
    tokens_out integer not null default 0,
    text       text,
    tool_calls jsonb,
    created_at timestamptz not null default now(),
    unique (run_id, seq)
);

create table if not exists public.agent_tool_call (
    id              bigint generated by default as identity primary key,
    run_step_id     bigint  not null unique references public.agent_run_step(id),
    tool_name       text    not null,
    args            jsonb   not null,
    result          jsonb   not null,
    ok              boolean not null,
    latency_ms      integer not null,
    idempotency_key text,
    created_at      timestamptz not null default now()
);


-- ============================================================================
-- SEED DATA
-- ============================================================================

insert into public.leave_student (roll_no, name, dept, leave_balance) values
    ('22CS045', 'Priya Raman',  'CSE', 8),
    ('22IT017', 'Arjun Kumar',  'IT',  1),
    ('22EC031', 'Divya Sekar',  'ECE', 0)
on conflict (roll_no) do nothing;

insert into public.leave_holiday (holiday_date, name) values
    ('2026-09-25', 'Founders Day'),
    ('2026-10-02', 'Gandhi Jayanti'),
    ('2026-10-20', 'Campus Festival')
on conflict (holiday_date) do nothing;

insert into public.leave_policy (name, value) values
    ('max_days_per_application', 5)
on conflict (name) do update set value = excluded.value;

-- One pre-existing approved leave, so "history" is not empty on a fresh run.
insert into public.leave_request (student_id, start_date, end_date, days, reason, status)
select s.id, '2026-09-15', '2026-09-15', 1, 'Already seeded leave', 'approved'
from public.leave_student s
where s.roll_no = '22EC031'
on conflict (student_id, start_date, end_date) do nothing;


-- ============================================================================
-- DOMAIN RPCS
--
-- Every side effect is one PostgreSQL transaction: check the key, do the work,
-- store the result. The tool cannot skip the policy or the balance check,
-- because the check is inside the function that does the write.
-- ============================================================================

drop function if exists public.apply_leave;

create or replace function public.apply_leave(
    p_student_id      bigint,
    p_start_date      date,
    p_end_date        date,
    p_days            integer,
    p_reason          text,
    p_idempotency_key text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    old_result     jsonb;
    s              public.leave_student%rowtype;
    existing       public.leave_request%rowtype;
    max_days       integer;
    new_request_id bigint;
    result         jsonb;
begin
    -- Same run, same step, same arguments: hand back what happened last time.
    select li.result into old_result
    from public.leave_idempotency li where li.key = p_idempotency_key;
    if old_result is not null then
        return old_result || jsonb_build_object('replayed', true);
    end if;

    if p_days <= 0 then
        result := jsonb_build_object('error', 'invalid_days');
    elsif p_start_date > p_end_date then
        result := jsonb_build_object('error', 'invalid_date_range');
    elsif length(trim(coalesce(p_reason, ''))) = 0 then
        result := jsonb_build_object('error', 'invalid_reason');
    else
        select lp.value into max_days
        from public.leave_policy lp where lp.name = 'max_days_per_application';

        if max_days is null then
            result := jsonb_build_object('error', 'policy_missing');
        elsif p_days > max_days then
            result := jsonb_build_object('error', 'policy_limit', 'max_days', max_days);
        else
            -- Lock the student row: two concurrent workers cannot both read
            -- balance 3, both see "enough", and both deduct.
            select * into s from public.leave_student
            where id = p_student_id for update;

            if not found then
                result := jsonb_build_object('error', 'unknown_student');
            else
                -- Look for an identical request BEFORE judging the balance.
                -- Otherwise repeating an application that already spent the
                -- balance reports insufficient_balance instead of
                -- already_applied, and the two backends disagree.
                select * into existing from public.leave_request
                where student_id = p_student_id
                  and start_date = p_start_date
                  and end_date   = p_end_date;

                if found then
                    result := jsonb_build_object(
                        'request_id', existing.id,
                        'status',     'already_applied',
                        'days',       existing.days);
                elsif p_days > s.leave_balance then
                    result := jsonb_build_object(
                        'error',     'insufficient_balance',
                        'balance',   s.leave_balance,
                        'requested', p_days);
                else
                    update public.leave_student
                    set leave_balance = leave_balance - p_days
                    where id = p_student_id;

                    insert into public.leave_request
                        (student_id, start_date, end_date, days, reason, status)
                    values
                        (p_student_id, p_start_date, p_end_date, p_days, p_reason, 'approved')
                    returning id into new_request_id;

                    result := jsonb_build_object(
                        'request_id', new_request_id,
                        'status',     'approved',
                        'days',       p_days);
                end if;
            end if;
        end if;
    end if;

    insert into public.leave_idempotency (key, tool_name, result)
    values (p_idempotency_key, 'apply_leave', result)
    on conflict (key) do nothing;

    return result;
end $$;


drop function if exists public.withdraw_leave;

create or replace function public.withdraw_leave(
    p_student_id      bigint,
    p_request_id      bigint,
    p_idempotency_key text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    old_result jsonb;
    r          public.leave_request%rowtype;
    result     jsonb;
begin
    select li.result into old_result
    from public.leave_idempotency li where li.key = p_idempotency_key;
    if old_result is not null then
        return old_result || jsonb_build_object('replayed', true);
    end if;

    select * into r from public.leave_request
    where id = p_request_id and student_id = p_student_id for update;

    if not found then
        result := jsonb_build_object('error', 'unknown_request');
    elsif r.status = 'withdrawn' then
        -- Safe to repeat on its own: the days are not restored twice.
        result := jsonb_build_object(
            'request_id', r.id, 'status', 'already_withdrawn', 'days_restored', 0);
    else
        update public.leave_student
        set leave_balance = leave_balance + r.days where id = p_student_id;
        update public.leave_request set status = 'withdrawn' where id = r.id;
        result := jsonb_build_object(
            'request_id', r.id, 'status', 'withdrawn', 'days_restored', r.days);
    end if;

    insert into public.leave_idempotency (key, tool_name, result)
    values (p_idempotency_key, 'withdraw_leave', result)
    on conflict (key) do nothing;

    return result;
end $$;


drop function if exists public.notify_hod;

create or replace function public.notify_hod(
    p_roll_no         text,
    p_message         text,
    p_idempotency_key text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    old_result  jsonb;
    existing_id bigint;
    daily_key   text;
    result      jsonb;
begin
    select li.result into old_result
    from public.leave_idempotency li where li.key = p_idempotency_key;
    if old_result is not null then
        return old_result || jsonb_build_object('replayed', true);
    end if;

    if length(trim(coalesce(p_message, ''))) = 0 or length(p_message) > 160 then
        result := jsonb_build_object('error', 'invalid_message');
    else
        -- Second layer, independent of the run: same student + same collapsed
        -- message + same day is one notification, whatever key arrives.
        -- Note '\s+' with ONE backslash. '\\s+' matches a literal backslash.
        daily_key := encode(sha256(convert_to(
              lower(trim(p_roll_no))
           || '|' || regexp_replace(trim(p_message), '\s+', ' ', 'g')
           || '|' || current_date::text, 'UTF8')), 'hex');

        insert into public.leave_notification (roll_no, message, dedupe_key)
        values (p_roll_no, p_message, daily_key)
        on conflict (dedupe_key) do nothing
        returning id into existing_id;

        if existing_id is null then
            select n.id into existing_id
            from public.leave_notification n where n.dedupe_key = daily_key;
            result := jsonb_build_object(
                'notification_id', existing_id, 'status', 'queued', 'duplicate', true);
        else
            result := jsonb_build_object(
                'notification_id', existing_id, 'status', 'queued', 'duplicate', false);
        end if;
    end if;

    insert into public.leave_idempotency (key, tool_name, result)
    values (p_idempotency_key, 'notify_hod', result)
    on conflict (key) do nothing;

    return result;
end $$;


-- Counting rows over PostgREST needs a column every table has. leave_policy is
-- keyed by name and leave_idempotency by key, so `select id` does not work for
-- them. One function keeps the client simple and the table list closed.
drop function if exists public.table_count;

create or replace function public.table_count(p_table text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare n bigint;
begin
    if p_table not in (
        'leave_student', 'leave_holiday', 'leave_policy', 'leave_request',
        'leave_notification', 'leave_idempotency', 'agent_thread',
        'agent_message', 'agent_run', 'agent_run_step', 'agent_tool_call') then
        raise exception 'unknown table %', p_table;
    end if;
    execute format('select count(*) from public.%I', p_table) into n;
    return n;
end $$;


drop function if exists public.healthcheck;

create or replace function public.healthcheck()
returns jsonb language sql
as $$ select jsonb_build_object('ok', true, 'service', 'leave-agent'); $$;


-- ============================================================================
-- AGENT RUNTIME RPCS: durable queue, leases, replay
-- ============================================================================

drop function if exists public.create_thread(uuid, text);
drop function if exists public.create_thread;

create or replace function public.create_thread(p_id uuid, p_student_id text)
returns uuid language plpgsql as $$
begin
    insert into public.agent_thread (id, student_id) values (p_id, p_student_id);
    return p_id;
end $$;


drop function if exists public.append_message;

create or replace function public.append_message(
    p_thread_id uuid, p_role text, p_text text)
returns integer language plpgsql as $$
declare n integer;
begin
    -- Lock the thread so two appends cannot pick the same seq.
    perform 1 from public.agent_thread where id = p_thread_id for update;
    select coalesce(max(m.seq), 0) + 1 into n
    from public.agent_message m where m.thread_id = p_thread_id;
    insert into public.agent_message (thread_id, seq, role, text)
    values (p_thread_id, n, p_role, p_text);
    return n;
end $$;


drop function if exists public.enqueue_run;

create or replace function public.enqueue_run(
    p_run_id uuid, p_thread_id uuid, p_text text,
    p_model text, p_max_attempts integer)
returns uuid language plpgsql as $$
begin
    -- The user's message and its queued run are saved together or not at all.
    perform public.append_message(p_thread_id, 'user', p_text);
    insert into public.agent_run
        (id, thread_id, status, model, max_attempts, available_at)
    values (p_run_id, p_thread_id, 'queued', p_model, p_max_attempts, now());
    return p_run_id;
end $$;


drop function if exists public.claim_next_run;

create or replace function public.claim_next_run(
    p_worker_id text, p_lease_seconds double precision)
returns table (run_id uuid, thread_id uuid, attempts integer)
language plpgsql as $$
declare r public.agent_run%rowtype;
begin
    -- SKIP LOCKED is what lets several workers poll the same queue without
    -- two of them claiming the same run.
    select * into r from public.agent_run
    where status = 'queued' and available_at <= now()
    order by available_at, created_at
    for update skip locked
    limit 1;

    if not found then
        return;
    end if;

    -- `attempts` is also an OUT column of this function, so the right-hand
    -- side must be qualified through an alias. Unqualified, PostgreSQL raises
    -- "column reference attempts is ambiguous" and no run is ever claimed.
    update public.agent_run ar
    set status      = 'running',
        lease_owner = p_worker_id,
        lease_until = now() + make_interval(secs => p_lease_seconds),
        attempts    = ar.attempts + 1,
        started_at  = coalesce(ar.started_at, now())
    where ar.id = r.id;

    return query select r.id, r.thread_id, r.attempts + 1;
end $$;


-- Returns a plain boolean, never an empty set: the Python side can read the
-- answer without guarding against a zero-row response.
drop function if exists public.heartbeat_run;

create or replace function public.heartbeat_run(
    p_run_id uuid, p_worker_id text, p_lease_seconds double precision)
returns boolean language plpgsql as $$
declare n integer;
begin
    update public.agent_run
    set lease_until = now() + make_interval(secs => p_lease_seconds)
    where id = p_run_id and status = 'running' and lease_owner = p_worker_id;
    get diagnostics n = row_count;
    return n = 1;
end $$;


drop function if exists public.reap_expired;

create or replace function public.reap_expired()
returns table (id uuid) language plpgsql as $$
declare r public.agent_run%rowtype;
begin
    for r in
        select * from public.agent_run
        where status = 'running' and lease_until < now()
        for update skip locked
    loop
        if r.attempts >= r.max_attempts then
            update public.agent_run
            set status = 'dead', error_code = 'lease_expired',
                lease_owner = null, lease_until = null, finished_at = now()
            where public.agent_run.id = r.id;
        else
            update public.agent_run
            set status = 'queued', error_code = 'lease_expired',
                lease_owner = null, lease_until = null, available_at = now()
            where public.agent_run.id = r.id;
        end if;
        id := r.id;
        return next;
    end loop;
end $$;


drop function if exists public.record_model_step;

create or replace function public.record_model_step(
    p_run_id uuid, p_seq integer, p_tokens_in integer,
    p_tokens_out integer, p_text text, p_tool_calls jsonb)
returns bigint language plpgsql as $$
declare sid bigint;
begin
    insert into public.agent_run_step
        (run_id, seq, kind, tokens_in, tokens_out, text, tool_calls)
    values (p_run_id, p_seq, 'model', p_tokens_in, p_tokens_out, p_text, p_tool_calls)
    returning agent_run_step.id into sid;

    update public.agent_run
    set tokens_in  = tokens_in  + p_tokens_in,
        tokens_out = tokens_out + p_tokens_out
    where agent_run.id = p_run_id;

    return sid;
end $$;


drop function if exists public.record_tool_call;

create or replace function public.record_tool_call(
    p_run_id uuid, p_seq integer, p_name text, p_args jsonb,
    p_result jsonb, p_ok boolean, p_latency_ms integer, p_idempotency_key text)
returns bigint language plpgsql as $$
declare sid bigint; tid bigint;
begin
    insert into public.agent_run_step (run_id, seq, kind)
    values (p_run_id, p_seq, 'tool')
    returning agent_run_step.id into sid;

    insert into public.agent_tool_call
        (run_step_id, tool_name, args, result, ok, latency_ms, idempotency_key)
    values (sid, p_name, p_args, p_result, p_ok, p_latency_ms, p_idempotency_key)
    returning agent_tool_call.id into tid;

    return tid;
end $$;


drop function if exists public.load_run_steps;

create or replace function public.load_run_steps(p_run_id uuid)
returns table (
    seq integer, kind text, step_text text, tool_calls jsonb,
    tool_name text, args jsonb, result jsonb, ok boolean)
language sql as $$
    select s.seq, s.kind, s.text, s.tool_calls,
           t.tool_name, t.args, t.result, t.ok
    from public.agent_run_step s
    left join public.agent_tool_call t on t.run_step_id = s.id
    where s.run_id = p_run_id
    order by s.seq;
$$;


drop function if exists public.complete_run;

create or replace function public.complete_run(
    p_run_id uuid, p_worker_id text, p_reply text)
returns boolean language plpgsql as $$
declare tid uuid;
begin
    -- Only the worker that still owns the run may finish it.
    select thread_id into tid from public.agent_run
    where id = p_run_id and status = 'running' and lease_owner = p_worker_id
    for update;

    if tid is null then
        return false;
    end if;

    perform public.append_message(tid, 'model', p_reply);
    update public.agent_run
    set status = 'succeeded', lease_owner = null, lease_until = null,
        error_code = null, finished_at = now()
    where id = p_run_id;

    return true;
end $$;


drop function if exists public.request_cancel;

create or replace function public.request_cancel(p_run_id uuid)
returns text language plpgsql as $$
declare s text;
begin
    select agent_run.status into s from public.agent_run
    where id = p_run_id for update;

    if s is null then
        return null;                       -- no such run
    elsif s = 'queued' then
        update public.agent_run
        set status = 'cancelled', finished_at = now() where id = p_run_id;
        return 'cancelled';
    elsif s = 'running' then
        -- Flag it. Its worker stops between steps, never mid tool call.
        update public.agent_run set cancel_requested = true where id = p_run_id;
    end if;
    return s;
end $$;


drop function if exists public.mark_cancelled;

create or replace function public.mark_cancelled(p_run_id uuid, p_worker_id text)
returns boolean language plpgsql as $$
declare n integer;
begin
    update public.agent_run
    set status = 'cancelled', lease_owner = null,
        lease_until = null, finished_at = now()
    where id = p_run_id and status = 'running' and lease_owner = p_worker_id;
    get diagnostics n = row_count;
    return n = 1;
end $$;


drop function if exists public.fail_attempt;

create or replace function public.fail_attempt(
    p_run_id uuid, p_worker_id text, p_error_code text,
    p_retryable boolean, p_backoff_seconds double precision default 2.0)
returns text language plpgsql as $$
declare a integer; mx integer; new_status text; delay_seconds double precision;
begin
    select attempts, max_attempts into a, mx from public.agent_run
    where id = p_run_id and status = 'running' and lease_owner = p_worker_id
    for update;

    if a is null then
        return null;                       -- this worker no longer owns it
    end if;

    if p_retryable and a < mx then
        delay_seconds := p_backoff_seconds * power(2, a - 1);
        update public.agent_run
        set status = 'queued', error_code = p_error_code,
            lease_owner = null, lease_until = null,
            available_at = now() + make_interval(secs => delay_seconds)
        where id = p_run_id;
        return 'queued';
    end if;

    new_status := case when p_retryable then 'dead' else 'failed' end;
    update public.agent_run
    set status = new_status, error_code = p_error_code,
        lease_owner = null, lease_until = null, finished_at = now()
    where id = p_run_id;
    return new_status;
end $$;


-- ============================================================================
-- ACCESS CONTROL
--
-- This repository is public, so the database is locked down on purpose.
-- Row Level Security is enabled on every table and NO policy is created, so
-- the anon and authenticated keys (the ones that could leak into a browser)
-- can read nothing. The service-role key bypasses RLS and is the only way in,
-- and it lives in .env, which is gitignored.
-- ============================================================================

alter table public.leave_student      enable row level security;
alter table public.leave_holiday      enable row level security;
alter table public.leave_policy       enable row level security;
alter table public.leave_request      enable row level security;
alter table public.leave_notification enable row level security;
alter table public.leave_idempotency  enable row level security;
alter table public.agent_thread       enable row level security;
alter table public.agent_message      enable row level security;
alter table public.agent_run          enable row level security;
alter table public.agent_run_step     enable row level security;
alter table public.agent_tool_call    enable row level security;

revoke all on all tables    in schema public from anon, authenticated;
revoke all on all functions in schema public from anon, authenticated;

grant usage                            on schema public            to service_role;
grant select, insert, update, delete   on all tables in schema public to service_role;
grant usage, select                    on all sequences in schema public to service_role;
grant execute                          on all functions in schema public to service_role;
